# Generated by Django 5.1.7 on 2025-03-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='homologation',
        ),
        migrations.AddField(
            model_name='task',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='testing',
            field=models.BooleanField(default=False),
        ),
    ]
