# Generated by Django 5.1.7 on 2025-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_task_homologation_task_in_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
