# Generated by Django 5.2 on 2025-06-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('progresso', models.CharField(choices=[('0', 'Novo'), ('1', 'Em andamento'), ('2', 'Pendente'), ('3', 'Cancelado'), ('4', 'Concluído')], default='0', max_length=1, verbose_name='Progresso')),
                ('dt_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data início')),
                ('dt_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data fim')),
                ('dt_conclusao_prev', models.DateTimeField(blank=True, null=True, verbose_name='Data conclusão prevista')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualização')),
            ],
        ),
    ]
