# Generated by Django 5.2 on 2025-05-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('progresso', models.CharField(choices=[('0', 'Novo'), ('1', 'Em andamento'), ('2', 'Pendente'), ('3', 'Cancelado'), ('4', 'Concluído')], default='0', max_length=1, verbose_name='Progresso')),
                ('dt_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data início')),
                ('dt_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data fim')),
                ('dt_conclusao_prev', models.DateTimeField(blank=True, null=True, verbose_name='Data conclusão prevista')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualização')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_designados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
