# Generated by Django 5.2 on 2025-06-06 17:41

import django.contrib.auth.base_user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_ticket_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='criado_por',
            field=models.ForeignKey(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
