# Generated by Django 5.2 on 2025-06-09 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_ticket_progresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.CharField(default='Novo', max_length=20, verbose_name='Progresso')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_progresso', to='planner.progresso'),
        ),
    ]
