# Generated by Django 5.2 on 2025-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_subticket_ticket_subticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subticket',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Status'),
        ),
    ]
