# Generated by Django 5.2 on 2025-06-10 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_subticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='subticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='conteudo',
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=0, verbose_name='Status')),
                ('dt_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data início')),
                ('dt_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data fim')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_criado', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_designado', to=settings.AUTH_USER_MODEL)),
                ('sub_ticket', models.ManyToManyField(related_name='projeto_ticket', to='planner.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='SubTicket',
        ),
    ]
