# Generated by Django 5.2 on 2025-06-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_remove_ticket_subticket_remove_ticket_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data atualização'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='dt_conclusao_prev',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data conclusão prevista'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progresso',
            field=models.ForeignKey(default='Novo', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_progresso', to='planner.progresso'),
        ),
        migrations.AlterUniqueTogether(
            name='progresso',
            unique_together={('progresso',)},
        ),
    ]
